import Header from '@/components/Header'
import Head from 'next/head'
import {getSession, useSession } from 'next-auth/react'
import Login from '@/components/Login'
import SideBar from '@/components/SideBar'
import Feed from '@/components/Feed'


export default function Home() {
  const {data:  session} = useSession()
return (
 session ? 
  <>
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<div className='bg-black text-white'>
  {/* Header  */}
<Header/>
<div className='w-full flex'>

{/* Left SideBar  */}
<SideBar />
<Feed />

</div>
  </div>    
  </>
  
: <Login />
)
}

// export async function getServerSidProps(context){
//   const session = await getSession(context)
// return {
//   props : {
//     session
//   }
// }
// }