import Header from '@/components/Header'
import Head from 'next/head'
import {getSession } from 'next-auth/react'
import Login from '@/components/Login'

export default function Home({session}) {
  if(!session) return <Login />
  return (
    <>
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<div className='bg-black text-white'>
  {/* Header  */}
<Header/>
{/* Left SideBar  */}
  </div>    
  </>
  )
}

export async function getServerSidProps(context){
const session = await getSession(context)
return {
  props : {
    session
  }
}
}